### PR TITLE
Add README info about playing native recorded audios

### PR DESCRIPTION
**Pull request by wmattei**

### CODE REVIEW

**Comment by ai** [comment]
Why current description is not working?

(Also, can you replace `chrome` to `Chrome`)

**Comment by wmattei** [comment]
It's because there isn't clear that audios recorder without the polyfill will not play on safari

**Comment by ai** [comment]
Can you make it shorter and more to the first paragraph?

**Comment by ai** [comment]
Right now text looks like arguing with `load polyfill only for Safari and Edge`. Do you not like this condition polyfill loading?

**Comment by wmattei** [comment]
Yes, i think that's the point, if you will just load the polyfill with these browser, and record something on Chrome for example, you won't be able to reproduce the recorded data in Safari (and probably not on edge as well) unless you pre-process it somehow. It's because native `MediaRecorder` always sets the mime type to `audio/ogg` which is not supported by Safari!

**Comment by ai** [comment]
Polyfill hurts performance for recording client and even using MP3 has 2x size compare to OGG.

I think file convertion on back-end is still the best option.

But we can mention that files from Chrome will not be playable in Safari and you need to convert them on back-end or force polyfill with MP3 encoder for everyone (with the price of client's performance).

**Comment by wmattei** [comment]
Totally agree, i changed the description, let me know if it's not clear enough!

**Comment by ai** [comment]
👍

**Pull request merged**
